package com.example.data.database

import android.content.Context
import androidx.datastore.preferences.core.booleanPreferencesKey
import androidx.datastore.preferences.core.doublePreferencesKey
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.longPreferencesKey
import androidx.datastore.preferences.core.stringPreferencesKey
import androidx.datastore.preferences.preferencesDataStore
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map

val Context.dataStore by preferencesDataStore(name = "classroom_settings")

data class LmsSettings(
    val schoolName: String = "Classroom LMS Institution",
    val reportHeader: String = "Official Student Term Progress Report",
    val reportFooter: String = "Generated by Classroom LMS • Confirmed Official Record",
    val signaturePlaceholder: String = "Class Teacher / Principal Signature",
    val backgroundTemplatePath: String? = null,
    val isLandscapeA4: Boolean = false,
    val isBiometricLockEnabled: Boolean = false,
    val hwWeight: Double = 20.0,
    val quizWeight: Double = 30.0,
    val projectWeight: Double = 20.0,
    val examWeight: Double = 30.0
)

open class PreferencesManager(private val context: Context) {
    companion object {
        val ACTIVE_CLASSROOM_ID = longPreferencesKey("active_classroom_id")
        val SCHOOL_NAME = stringPreferencesKey("school_name")
        val REPORT_HEADER = stringPreferencesKey("report_header")
        val REPORT_FOOTER = stringPreferencesKey("report_footer")
        val SIGNATURE_PLACEHOLDER = stringPreferencesKey("signature_placeholder")
        val BG_TEMPLATE_PATH = stringPreferencesKey("background_template_path")
        val IS_LANDSCAPE_A4 = booleanPreferencesKey("is_landscape_a4")
        val IS_BIOMETRIC_LOCK_ENABLED = booleanPreferencesKey("is_biometric_lock_enabled")
        val WEIGHT_HW = doublePreferencesKey("weight_homework")
        val WEIGHT_QUIZ = doublePreferencesKey("weight_quiz")
        val WEIGHT_PROJECT = doublePreferencesKey("weight_project")
        val WEIGHT_EXAM = doublePreferencesKey("weight_exam")
    }

    open val activeClassroomIdFlow: Flow<Long?> = context.dataStore.data
        .map { preferences ->
            val id = preferences[ACTIVE_CLASSROOM_ID]
            if (id == -1L) null else id
        }

    open val settingsFlow: Flow<LmsSettings> = context.dataStore.data
        .map { preferences ->
            LmsSettings(
                schoolName = preferences[SCHOOL_NAME] ?: "Classroom LMS Institution",
                reportHeader = preferences[REPORT_HEADER] ?: "Official Student Term Progress Report",
                reportFooter = preferences[REPORT_FOOTER] ?: "Generated by Classroom LMS • Confirmed Official Record",
                signaturePlaceholder = preferences[SIGNATURE_PLACEHOLDER] ?: "Class Teacher / Principal Signature",
                backgroundTemplatePath = preferences[BG_TEMPLATE_PATH],
                isLandscapeA4 = preferences[IS_LANDSCAPE_A4] ?: false,
                isBiometricLockEnabled = preferences[IS_BIOMETRIC_LOCK_ENABLED] ?: false,
                hwWeight = preferences[WEIGHT_HW] ?: 20.0,
                quizWeight = preferences[WEIGHT_QUIZ] ?: 30.0,
                projectWeight = preferences[WEIGHT_PROJECT] ?: 20.0,
                examWeight = preferences[WEIGHT_EXAM] ?: 30.0
            )
        }

    open suspend fun saveActiveClassroomId(id: Long?) {
        context.dataStore.edit { preferences ->
            if (id != null) {
                preferences[ACTIVE_CLASSROOM_ID] = id
            } else {
                preferences.remove(ACTIVE_CLASSROOM_ID)
            }
        }
    }

    open suspend fun saveSettings(settings: LmsSettings) {
        context.dataStore.edit { preferences ->
            preferences[SCHOOL_NAME] = settings.schoolName
            preferences[REPORT_HEADER] = settings.reportHeader
            preferences[REPORT_FOOTER] = settings.reportFooter
            preferences[SIGNATURE_PLACEHOLDER] = settings.signaturePlaceholder
            if (settings.backgroundTemplatePath != null) {
                preferences[BG_TEMPLATE_PATH] = settings.backgroundTemplatePath
            } else {
                preferences.remove(BG_TEMPLATE_PATH)
            }
            preferences[IS_LANDSCAPE_A4] = settings.isLandscapeA4
            preferences[IS_BIOMETRIC_LOCK_ENABLED] = settings.isBiometricLockEnabled
            preferences[WEIGHT_HW] = settings.hwWeight
            preferences[WEIGHT_QUIZ] = settings.quizWeight
            preferences[WEIGHT_PROJECT] = settings.projectWeight
            preferences[WEIGHT_EXAM] = settings.examWeight
        }
    }
}