package com.example.ui.screens

import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.PickVisualMediaRequest
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Image
import androidx.compose.material.icons.filled.Save
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import coil.compose.AsyncImage
import com.example.ui.viewmodel.ClassroomViewModel
import com.example.ui.viewmodel.LmsUiState
import java.io.File

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SettingsScreen(
    uiState: LmsUiState,
    viewModel: ClassroomViewModel,
    onDismiss: () -> Unit
) {
    var schoolName by remember { mutableStateOf("Classroom LMS Institution") }
    var reportHeader by remember { mutableStateOf("Official Student Term Progress Report") }
    var reportFooter by remember { mutableStateOf("Generated by Classroom LMS • Confirmed Official Record") }
    var signaturePlaceholder by remember { mutableStateOf("Class Teacher / Principal Signature") }
    var backgroundTemplatePath by remember { mutableStateOf<String?>(null) }
    var isLandscapeA4 by remember { mutableStateOf(false) }

    // Grading Rules & Weightage
    var hwWeight by remember { mutableStateOf("20") }
    var quizWeight by remember { mutableStateOf("30") }
    var projectWeight by remember { mutableStateOf("20") }
    var examWeight by remember { mutableStateOf("30") }

    val imagePickerLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.PickVisualMedia()
    ) { uri: Uri? ->
        if (uri != null) {
            backgroundTemplatePath = uri.toString()
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Settings Hub & Templates", fontWeight = FontWeight.Bold) },
                navigationIcon = {
                    IconButton(onClick = onDismiss) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
                actions = {
                    IconButton(onClick = {
                        viewModel.showToast("Settings & Templates Saved Successfully!")
                        onDismiss()
                    }) {
                        Icon(Icons.Default.Save, contentDescription = "Save")
                    }
                }
            )
        }
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // SECTION 1: EXAM, REPORT & PORTFOLIO TEMPLATE CUSTOMIZATION
            Card(
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(16.dp),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)
            ) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                    Text(
                        text = "Exam, Report & Portfolio Templates",
                        fontSize = 16.sp,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.primary
                    )
                    Text(
                        text = "Create Exam Marks Templates, customize headers, footers, and upload background A4 images for official PDF exports.",
                        fontSize = 12.sp,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )

                    OutlinedTextField(
                        value = schoolName,
                        onValueChange = { schoolName = it },
                        label = { Text("Institution / School Name") },
                        singleLine = true,
                        modifier = Modifier.fillMaxWidth()
                    )

                    OutlinedTextField(
                        value = reportHeader,
                        onValueChange = { reportHeader = it },
                        label = { Text("Default Report Header Title") },
                        singleLine = true,
                        modifier = Modifier.fillMaxWidth()
                    )

                    OutlinedTextField(
                        value = reportFooter,
                        onValueChange = { reportFooter = it },
                        label = { Text("Default Report Footer Text") },
                        singleLine = true,
                        modifier = Modifier.fillMaxWidth()
                    )

                    OutlinedTextField(
                        value = signaturePlaceholder,
                        onValueChange = { signaturePlaceholder = it },
                        label = { Text("Signature Line Placeholder") },
                        singleLine = true,
                        modifier = Modifier.fillMaxWidth()
                    )

                    Spacer(modifier = Modifier.height(8.dp))
                    Text(
                        text = "Create Exam Marks Template (PDF Background Overlay)",
                        fontSize = 13.sp,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.onSurface
                    )
                    Text(
                        text = "Upload a designed A4 school letterhead or marksheet layout. Exam results will be overlaid onto this image.",
                        fontSize = 11.sp,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )

                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(12.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Button(onClick = {
                            imagePickerLauncher.launch(
                                PickVisualMediaRequest(ActivityResultContracts.PickVisualMedia.ImageOnly)
                            )
                        }) {
                            Icon(Icons.Default.Image, contentDescription = null, modifier = Modifier.size(18.dp))
                            Spacer(modifier = Modifier.width(6.dp))
                            Text("Upload Background")
                        }

                        if (backgroundTemplatePath != null) {
                            Text(
                                text = "Background Selected",
                                fontSize = 12.sp,
                                color = MaterialTheme.colorScheme.primary,
                                fontWeight = FontWeight.Bold
                            )
                        } else {
                            Text(
                                text = "No background image",
                                fontSize = 12.sp,
                                color = MaterialTheme.colorScheme.onSurfaceVariant
                            )
                        }
                    }

                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text("A4 Orientation: ${if (isLandscapeA4) "Landscape" else "Portrait"}", fontSize = 13.sp)
                        Switch(
                            checked = isLandscapeA4,
                            onCheckedChange = { isLandscapeA4 = it }
                        )
                    }
                }
            }

            // SECTION 2: GRADING RULES & CATEGORY WEIGHTAGE
            Card(
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(16.dp),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)
            ) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                    Text(
                        text = "Grading Rules & Category Weightage",
                        fontSize = 16.sp,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.primary
                    )
                    Text(
                        text = "Set category weight percentages for final grade and GPA calculations (must sum to 100%):",
                        fontSize = 12.sp,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )

                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        OutlinedTextField(
                            value = hwWeight,
                            onValueChange = { hwWeight = it },
                            label = { Text("Homework %") },
                            singleLine = true,
                            modifier = Modifier.weight(1f)
                        )
                        OutlinedTextField(
                            value = quizWeight,
                            onValueChange = { quizWeight = it },
                            label = { Text("Quizzes %") },
                            singleLine = true,
                            modifier = Modifier.weight(1f)
                        )
                    }

                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        OutlinedTextField(
                            value = projectWeight,
                            onValueChange = { projectWeight = it },
                            label = { Text("Projects %") },
                            singleLine = true,
                            modifier = Modifier.weight(1f)
                        )
                        OutlinedTextField(
                            value = examWeight,
                            onValueChange = { examWeight = it },
                            label = { Text("Exams %") },
                            singleLine = true,
                            modifier = Modifier.weight(1f)
                        )
                    }

                    val totalWeight = (hwWeight.toIntOrNull() ?: 0) +
                            (quizWeight.toIntOrNull() ?: 0) +
                            (projectWeight.toIntOrNull() ?: 0) +
                            (examWeight.toIntOrNull() ?: 0)

                    Text(
                        text = "Total Weight: $totalWeight% ${if (totalWeight == 100) "✓ Valid" else "⚠️ Must equal 100%"}",
                        fontSize = 13.sp,
                        fontWeight = FontWeight.Bold,
                        color = if (totalWeight == 100) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.error
                    )
                }
            }

            Button(
                onClick = {
                    viewModel.showToast("Settings & Templates Saved Successfully!")
                    onDismiss()
                },
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(12.dp)
            ) {
                Text("Save All Settings & Rules", fontWeight = FontWeight.Bold, fontSize = 15.sp)
            }
        }
    }
}
